### ISSUE TITLE
Docs site

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/vue-data-component#19]

**Comment by WouterCypers** [comment]
Is there any progress on finishing the doc's? Would love to use the component but its difficult to understand without documentation.

Keep up the good work!

**Comment by sebastiandedeyne** [comment]
Hi Wouter!

I haven't finished the docs yet because there are still a few things I'm unsure about with this package...

May I ask how you'd specifically be using this library? That might help me make some decisions :)

**Comment by WouterCypers** [comment]
Hi Sebastian!

We're making a customer portal where customers can see lists of their products, invoices, contacts, etc. These lists/tables are quite different form each other, except for that they each need to be paginated, sortable and filterable. The "renderless" aspect of vue-data-component is what seems most interesting to us, as defining our own view is very important. We understand it's very hard to maintain a full documentation, but an explained example would already be cool!

Greetings from Leuven :)

**Comment by sebastiandedeyne** [comment]
I'm gonna try to invest some time in this later this week. Sorry for the wait! But there are still a few parts I'm not 100% happy about, so I wanna be sure I'm not gonna be changing the API anymore before documenting everything...

**Comment by ziming** [comment]
Looking forward to it!

**Comment by sebastiandedeyne** [comment]
Sorry, but due to us working on other projects and not really needing this in the near future, this is on hold for now.
