### ISSUE TITLE
Rework initial load delay handling

### ISSUE THREAD

**Issue by sebastiandedeyne** [spatie/vue-data-component#34]
The initial load delay is meant to hide the component before the data is loaded, to prevent unnecessary rerenders and layout jumps.

Originally, this meant that when we were in the delay, the component didn't render. The problem with this approach is that you lose the flexibility to handle the initial loading state yourself with a placeholder of some sorts.

This flexibility is great! But the initial use case, hiding the component in the initial load delay, became harder. The package user needs to implement their own `v-if` now.

How can we make both camps happy? The only option I can think of:

- Add a prop that dictates whether or not we should render the component in the initial load delay

Or maybe we could do something with slots?

Not sure what's best, up for discussion.

**Comment by AdrianMrn** [comment]
>The package user needs to implement their own v-if now.

I'm not a fan of this. It seems redundant that the user would have to copy+paste `v-if="isInitialLoadDelayFinished"` onto every data-component. <br><br>

>Or maybe we could do something with slots?

Agreed. Maybe something like this?
```vue
<slot v-if="(initialLoadDelayMs && !isInitialLoadDelayFinished)" name="placeholder"></slot>
```
This way, the user doesn't have to scope out any props and can just provide a loading placeholder/spinner/whatever. They can also choose to leave the loader prop empty so the data-component's behaviour stays the same.

**Comment by AdrianMrn** [comment]
@sebastiandedeyne I forgot. Was my suggestion OK & can I start implementing it like that?

**Comment by sebastiandedeyne** [comment]
Yup! We just decided to call it `placeholder` instead of `loader`, which was alrady edited in your previous comment
